baseurl: "/Samen-Onder-Handbereik"
apiname: "Samen Onder Handbereik"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.

nav:
  - title: Samen Onder Handbereik
    subnav:
      - title: Main
        path: /
  - title: Samenwerkfuncties
    subnav:
      - title: Sub 1
        path: /samenwerkfuncties-sub1
  - title: Architectuur
    subnav:
      - title: Sub 1
        path: /architectuur-sub1
  - title: API's 
    subnav:
      - title: Melding API (swagger)
        path: /swagger-ui
      - title: Melding API (redoc)
        path: /redoc

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: Ewout124/jekyll-theme-soh

github: Ewout124/Samen-Onder-Handbereik

theme: jekyll-theme-time-machine

project_name: /Samen-Onder-Handbereik

# standard_family: Omgevingswet
